### ISSUE TITLE
Necessary code removed from Start2.sh in PR#10

### ISSUE THREAD

**Issue by waqarz** [haudiobe/ATSC_ROUTE#12]
This code was doing the necessary handling of open-source/proprietary switch, was removed in https://github.com/waqarz/ATSC_ROUTE/pull/10 by @AdithyanIlangovan :

if [ -f "Hotel/MultiRate.mpd" ]
then
    DASHContent=Hotel
else
    DASHContent=ToS
fi

if [ -f "Wave/MultiRate.mpd" ]
then
    DASHContent2=Wave
else
    DASHContent2=Sintel
fi

**Comment by AdithyanIlangovan** [comment]
Added back in PR #13.
