### ISSUE TITLE
Problem with network interface detection

### ISSUE THREAD

**Issue by DerouineauNicolas** [haudiobe/ATSC_ROUTE#18]
There might be an issue in the onloadaction.php script on the Sender_UI.

I see that the script is parsing the result of "sudo ifconfig" to get the ip address. It looks for the "inet addr" pattern. 

Here is the result of my "sudo ifconfig" on my machine.

enp0s25: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet "someip" netmask 255.255.254.0  broadcast x.x.x.x
        inet6 "someip"  prefixlen 64  scopeid 0x0<global>
        inet6 "someip"  prefixlen 64  scopeid 0x0<global>
        inet6 "someip"  prefixlen 64  scopeid 0x20<link>
        ether "someip"   txqueuelen 1000  (Ethernet)
        RX packets 2511788  bytes 3336052834 (3.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1196753  bytes 95430760 (91.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf3400000-f3420000 

As you can see, there is no "inet addr" pattern. I modified the script to check for just "inet" and remove the 5 first character and the sender seems to be working (ie: I see the two multicast upd packets on wireshark). But on the receiver  side, the "tuning in" message is stuck.

**Comment by waqarz** [comment]
To understand which linux/version are you using?

Can you see any files/segments being recieved in the channel you are tuning to e.g. in Work/Route_Receiver/Receiver/DASH_Content1 if you select channel 1?

**Comment by DerouineauNicolas** [comment]
I just realise that I have been reading the README too fast... I'm using a debian 64 bits, so this explains the difference for the ifconfig compared to Ubuntu. I don't see any files/segments in DASH1_content1 folder.
I'm going to try under Ubuntu. Sorry about the mistake.
